"""Curated city-break destinations reachable from western Poland.

Only airports listed in AIRPORTS are considered; beach-resort airports (Canaries, Greek islands,
Cyprus, Antalya, Hurghada...) are deliberately absent. Transfer notes are approximate travel
times from the airport to the centre, shown to the user as "orientacyjnie".
`hotel_night` is a rough PLN/night estimate for 2 adults (rating ≥ 8, near the centre, off-season);
it is used only to pre-rank candidates before real hotel prices are fetched and is never displayed.
"""
from __future__ import annotations

import zlib

ACCENTS = ("ochre", "coral", "teal", "blue", "rose", "olive")

# key: (name, country, cc, lat, lon, hotel_night, tagline)
CITIES: dict[str, tuple] = {
    "barcelona": ("Barcelona", "Hiszpania", "ES", 41.3870, 2.1701, 520, "Gaudí, tapas i plaża w granicach miasta."),
    "madryt": ("Madryt", "Hiszpania", "ES", 40.4169, -3.7035, 450, "Prado, Retiro i najdłuższe kolacje w Europie."),
    "walencja": ("Walencja", "Hiszpania", "ES", 39.4699, -0.3763, 380, "Miasto Sztuki i Nauki, paella u źródła i plaża."),
    "sewilla": ("Sewilla", "Hiszpania", "ES", 37.3861, -5.9926, 400, "Alcázar, flamenco i pomarańcze na ulicach."),
    "malaga": ("Malaga", "Hiszpania", "ES", 36.7202, -4.4203, 400, "Picasso, twierdza Alcazaba i ciepło także zimą."),
    "alicante": ("Alicante", "Hiszpania", "ES", 38.3452, -0.4810, 330, "Zamek nad miastem, promenada i słońce do listopada."),
    "palma": ("Palma", "Hiszpania", "ES", 39.5696, 2.6502, 420, "Gotycka katedra nad morzem i stare miasto Majorki."),
    "bilbao": ("Bilbao", "Hiszpania", "ES", 43.2630, -2.9350, 400, "Guggenheim, pintxos i baskijski charakter."),
    "lizbona": ("Lizbona", "Portugalia", "PT", 38.7139, -9.1394, 450, "Tramwaj 28, pastéis de nata i widoki z miradouros."),
    "porto": ("Porto", "Portugalia", "PT", 41.1579, -8.6291, 380, "Ribeira nad Douro, piwnice wina porto i azulejos."),
    "rzym": ("Rzym", "Włochy", "IT", 41.8960, 12.4823, 480, "Koloseum, Watykan i carbonara tam, gdzie ją wymyślono."),
    "mediolan": ("Mediolan", "Włochy", "IT", 45.4642, 9.1900, 480, "Katedra Duomo, Ostatnia Wieczerza i aperitivo w Navigli."),
    "bolonia": ("Bolonia", "Włochy", "IT", 44.4938, 11.3426, 420, "Arkady, wieże i najlepsza kuchnia we Włoszech."),
    "neapol": ("Neapol", "Włochy", "IT", 40.8390, 14.2526, 360, "Pizza, Wezuwiusz na horyzoncie i blisko do Pompejów."),
    "wenecja": ("Wenecja", "Włochy", "IT", 45.4380, 12.3358, 620, "Kanały, gondole i zaułki bez samochodów."),
    "werona": ("Werona", "Włochy", "IT", 45.4390, 10.9940, 400, "Arena, balkon Julii i blisko nad Gardę."),
    "turyn": ("Turyn", "Włochy", "IT", 45.0703, 7.6869, 380, "Muzeum Egipskie, kawa bicerin i Alpy w tle."),
    "bari": ("Bari", "Włochy", "IT", 41.1280, 16.8700, 340, "Stare miasto Apulii, orecchiette i wypad do Alberobello."),
    "palermo": ("Palermo", "Włochy", "IT", 38.1157, 13.3615, 340, "Targi uliczne, barok i street food Sycylii."),
    "katania": ("Katania", "Włochy", "IT", 37.5021, 15.0872, 330, "Etna nad miastem, targ rybny i barok z lawy."),
    "piza": ("Piza", "Włochy", "IT", 43.7230, 10.3966, 360, "Krzywa wieża, a Florencja godzinę pociągiem."),
    "florencja": ("Florencja", "Włochy", "IT", 43.7710, 11.2540, 520, "Renesans na każdym rogu: Uffizi, Duomo, Ponte Vecchio."),
    "genua": ("Genua", "Włochy", "IT", 44.4070, 8.9340, 360, "Port, pesto i blisko do Cinque Terre."),
    "cagliari": ("Cagliari", "Włochy", "IT", 39.2170, 9.1130, 350, "Stolica Sardynii: bastiony i plaża Poetto."),
    "triest": ("Triest", "Włochy", "IT", 45.6500, 13.7680, 360, "Kawiarnie Habsburgów nad Adriatykiem."),
    "paryz": ("Paryż", "Francja", "FR", 48.8566, 2.3522, 650, "Luwr, Montmartre i croissant o poranku."),
    "nicea": ("Nicea", "Francja", "FR", 43.6966, 7.2700, 520, "Promenade des Anglais i blisko do Monako."),
    "marsylia": ("Marsylia", "Francja", "FR", 43.2951, 5.3740, 420, "Stary Port, bouillabaisse i calanques."),
    "lyon": ("Lyon", "Francja", "FR", 45.7578, 4.8320, 420, "Stolica francuskiej kuchni i renesansowe traboules."),
    "bordeaux": ("Bordeaux", "Francja", "FR", 44.8410, -0.5730, 420, "Plac Giełdowy, Cité du Vin i winnice w okolicy."),
    "tuluza": ("Tuluza", "Francja", "FR", 43.6045, 1.4440, 380, "Różowe miasto: ceglane place i Airbus."),
    "londyn": ("Londyn", "Wielka Brytania", "GB", 51.5080, -0.1281, 700, "Muzea za darmo, West End i targi uliczne."),
    "edynburg": ("Edynburg", "Wielka Brytania", "GB", 55.9500, -3.1883, 550, "Zamek na skale, Royal Mile i whisky."),
    "manchester": ("Manchester", "Wielka Brytania", "GB", 53.4794, -2.2453, 450, "Futbol, muzyka i ceglane dzielnice."),
    "liverpool": ("Liverpool", "Wielka Brytania", "GB", 53.4050, -2.9880, 400, "Beatlesi, Anfield i nabrzeże Albert Dock."),
    "bristol": ("Bristol", "Wielka Brytania", "GB", 51.4545, -2.5970, 430, "Banksy, most wiszący i portowy klimat."),
    "glasgow": ("Glasgow", "Wielka Brytania", "GB", 55.8610, -4.2500, 420, "Architektura Mackintosha, muzea i puby z muzyką."),
    "belfast": ("Belfast", "Wielka Brytania", "GB", 54.5970, -5.9300, 420, "Titanic Belfast i wypad na Grobli Olbrzyma."),
    "dublin": ("Dublin", "Irlandia", "IE", 53.3470, -6.2590, 650, "Temple Bar, Guinness i Trinity College."),
    "cork": ("Cork", "Irlandia", "IE", 51.8980, -8.4730, 450, "English Market i zielone wybrzeże Irlandii."),
    "bruksela": ("Bruksela", "Belgia", "BE", 50.8467, 4.3525, 450, "Grand-Place, gofry i blisko do Brugii."),
    "amsterdam": ("Amsterdam", "Holandia", "NL", 52.3730, 4.8930, 700, "Kanały, rowery i Rijksmuseum."),
    "eindhoven": ("Eindhoven", "Holandia", "NL", 51.4400, 5.4780, 380, "Miasto designu, a do Amsterdamu 1 h 20 min pociągiem."),
    "rotterdam": ("Rotterdam", "Holandia", "NL", 51.9220, 4.4790, 450, "Nowoczesna architektura i Markthal."),
    "luksemburg": ("Luksemburg", "Luksemburg", "LU", 49.6110, 6.1300, 500, "Kazamaty, wąwozy i darmowa komunikacja."),
    "monachium": ("Monachium", "Niemcy", "DE", 48.1374, 11.5755, 480, "Marienplatz, piwiarnie i Alpy na horyzoncie."),
    "hamburg": ("Hamburg", "Niemcy", "DE", 53.5503, 9.9930, 450, "Speicherstadt, Elbphilharmonie i port."),
    "kolonia": ("Kolonia", "Niemcy", "DE", 50.9410, 6.9580, 420, "Katedra, Ren i piwo Kölsch."),
    "dusseldorf": ("Düsseldorf", "Niemcy", "DE", 51.2260, 6.7730, 420, "Stare miasto nad Renem i Königsallee."),
    "frankfurt": ("Frankfurt", "Niemcy", "DE", 50.1100, 8.6820, 450, "Wieżowce nad Menem i jabłecznik w Sachsenhausen."),
    "wieden": ("Wiedeń", "Austria", "AT", 48.2082, 16.3738, 450, "Kawiarnie, pałace Habsburgów i sznycel."),
    "salzburg": ("Salzburg", "Austria", "AT", 47.8000, 13.0440, 450, "Mozart, twierdza i Alpy tuż za miastem."),
    "praga": ("Praga", "Czechy", "CZ", 50.0870, 14.4210, 380, "Most Karola, Hradczany i czeskie piwo."),
    "budapeszt": ("Budapeszt", "Węgry", "HU", 47.4970, 19.0510, 350, "Termy, ruin bary i Parlament nad Dunajem."),
    "bratyslawa": ("Bratysława", "Słowacja", "SK", 48.1440, 17.1070, 330, "Kompaktowe stare miasto, a Wiedeń godzinę stąd."),
    "genewa": ("Genewa", "Szwajcaria", "CH", 46.2040, 6.1430, 750, "Jezioro Genewskie, fontanna Jet d'Eau i Alpy."),
    "zurych": ("Zurych", "Szwajcaria", "CH", 47.3720, 8.5400, 750, "Jezioro, starówka i szwajcarska precyzja."),
    "bazylea": ("Bazylea", "Szwajcaria", "CH", 47.5580, 7.5870, 650, "Sztuka, Ren i trzy kraje w zasięgu tramwaju."),
    "kopenhaga": ("Kopenhaga", "Dania", "DK", 55.6761, 12.5683, 650, "Nyhavn, rowery i nowa kuchnia nordycka."),
    "oslo": ("Oslo", "Norwegia", "NO", 59.9130, 10.7390, 600, "Opera, muzea Muncha i fiord w centrum."),
    "bergen": ("Bergen", "Norwegia", "NO", 60.3970, 5.3240, 600, "Kolorowe Bryggen i brama do fiordów."),
    "sztokholm": ("Sztokholm", "Szwecja", "SE", 59.3250, 18.0710, 600, "Gamla Stan, muzeum Vasa i wyspy archipelagu."),
    "goteborg": ("Göteborg", "Szwecja", "SE", 57.7070, 11.9670, 500, "Kanały, owoce morza i szkiery."),
    "malmo": ("Malmö", "Szwecja", "SE", 55.6050, 13.0000, 450, "Turning Torso, a Kopenhaga 35 min pociągiem."),
    "helsinki": ("Helsinki", "Finlandia", "FI", 60.1700, 24.9410, 500, "Design, sauny i twierdza Suomenlinna."),
    "rejkiawik": ("Rejkiawik", "Islandia", "IS", 64.1470, -21.9400, 800, "Zorza, gejzery i Błękitna Laguna."),
    "ryga": ("Ryga", "Łotwa", "LV", 56.9490, 24.1050, 330, "Secesja, stare miasto i Bałtyk w Jurmali."),
    "tallinn": ("Tallinn", "Estonia", "EE", 59.4370, 24.7450, 380, "Średniowieczne mury i cyfrowa stolica."),
    "wilno": ("Wilno", "Litwa", "LT", 54.6870, 25.2800, 330, "Ostra Brama, barok i polskie ślady."),
    "ateny": ("Ateny", "Grecja", "GR", 37.9755, 23.7348, 400, "Akropol, Plaka i ciepło do listopada."),
    "saloniki": ("Saloniki", "Grecja", "GR", 40.6330, 22.9410, 330, "Bizancjum, promenada i najlepsze bougatsa."),
    "split": ("Split", "Chorwacja", "HR", 43.5080, 16.4400, 380, "Pałac Dioklecjana i promenada Riva."),
    "dubrownik": ("Dubrownik", "Chorwacja", "HR", 42.6410, 18.1100, 480, "Mury miejskie nad Adriatykiem."),
    "zadar": ("Zadar", "Chorwacja", "HR", 44.1150, 15.2240, 330, "Organy morskie i zachody słońca."),
    "zagrzeb": ("Zagrzeb", "Chorwacja", "HR", 45.8130, 15.9770, 320, "Górne Miasto, kawiarnie i jarmarki."),
    "lublana": ("Lublana", "Słowenia", "SI", 46.0510, 14.5060, 400, "Zielona stolica nad Lublanicą, blisko do Bledu."),
    "belgrad": ("Belgrad", "Serbia", "RS", 44.8160, 20.4600, 280, "Twierdza nad Dunajem i nocne życie."),
    "sarajewo": ("Sarajewo", "Bośnia i Hercegowina", "BA", 43.8590, 18.4310, 250, "Baščaršija, kawa po bośniacku i historia."),
    "tirana": ("Tirana", "Albania", "AL", 41.3280, 19.8180, 250, "Kolorowe bloki, bunkry i tanio."),
    "sofia": ("Sofia", "Bułgaria", "BG", 42.6970, 23.3220, 260, "Sobór Newskiego i góra Witosza nad miastem."),
    "bukareszt": ("Bukareszt", "Rumunia", "RO", 44.4350, 26.1000, 280, "Pałac Parlamentu i stare miasto Lipscani."),
    "malta": ("Malta", "Malta", "MT", 35.8980, 14.5130, 400, "Valletta, Mdina i morze nawet w listopadzie."),
    "stambul": ("Stambuł", "Turcja", "TR", 41.0060, 28.9760, 350, "Hagia Sophia, bazary i Bosfor."),
    "dortmund": ("Dortmund", "Niemcy", "DE", 51.5136, 7.4653, 380, "Signal Iduna Park, muzeum futbolu i Zagłębie Ruhry."),
    "kiszyniow": ("Kiszyniów", "Mołdawia", "MD", 47.0105, 28.8638, 220, "Piwnice winne Cricova i Mileștii Mici, a do tego tanio."),
    "ochryda": ("Ochryda", "Macedonia Północna", "MK", 41.1172, 20.8016, 250, "Stare miasto nad Jeziorem Ochrydzkim, cerkwie nad wodą."),
}

# IATA: (city key, via-airport label or None, transfer note)
AIRPORTS: dict[str, tuple] = {
    "BCN": ("barcelona", None, "Aerobus do placu Katalońskiego, ok. 35 min."),
    "GRO": ("barcelona", "Girona", "Autobus Girona–Barcelona, ok. 1 h 15 min. Do centrum Girony ok. 20 min."),
    "MAD": ("madryt", None, "Metro linii 8 lub autobus Exprés Aeropuerto, ok. 40 min."),
    "VLC": ("walencja", None, "Metro, ok. 25 min do centrum."),
    "SVQ": ("sewilla", None, "Autobus EA, ok. 35 min do centrum."),
    "AGP": ("malaga", None, "Pociąg podmiejski C1, ok. 12 min do centrum."),
    "ALC": ("alicante", None, "Autobus C-6, ok. 25 min do centrum."),
    "PMI": ("palma", None, "Autobus A1, ok. 25 min do centrum."),
    "BIO": ("bilbao", None, "Autobus Bizkaibus, ok. 20 min do centrum."),
    "LIS": ("lizbona", None, "Metro (linia czerwona), ok. 25 min do centrum."),
    "OPO": ("porto", None, "Metro linii E, ok. 30 min do centrum."),
    "FCO": ("rzym", None, "Pociąg Leonardo Express, 32 min do dworca Termini."),
    "CIA": ("rzym", "Ciampino", "Autobus do dworca Termini, ok. 40 min."),
    "BGY": ("mediolan", "Bergamo", "Autobus do Milano Centrale, ok. 1 h. Stare miasto Bergamo: ok. 20 min."),
    "MXP": ("mediolan", "Malpensa", "Pociąg Malpensa Express, ok. 50 min do centrum."),
    "LIN": ("mediolan", "Linate", "Metro M4, ok. 15 min do centrum."),
    "BLQ": ("bolonia", None, "Kolejka Marconi Express, ok. 7 min do dworca."),
    "NAP": ("neapol", None, "Autobus Alibus, ok. 20 min do centrum."),
    "VCE": ("wenecja", None, "Autobus do Piazzale Roma, ok. 25 min."),
    "TSF": ("wenecja", "Treviso", "Autobus do Piazzale Roma, ok. 1 h 10 min."),
    "VRN": ("werona", None, "Autobus Aerobus, ok. 15 min do dworca Porta Nuova."),
    "TRN": ("turyn", None, "Pociąg lub autobus, ok. 40 min do centrum."),
    "BRI": ("bari", None, "Pociąg, ok. 20 min do centrum."),
    "PMO": ("palermo", None, "Pociąg lub autobus, ok. 50 min do centrum."),
    "CTA": ("katania", None, "Autobus Alibus, ok. 25 min do centrum."),
    "PSA": ("piza", None, "Kolejka Pisamover, 5 min do dworca. Florencja: ok. 1 h pociągiem."),
    "FLR": ("florencja", None, "Tramwaj T2, ok. 20 min do centrum."),
    "GOA": ("genua", None, "Autobus Volabus, ok. 20 min do centrum."),
    "CAG": ("cagliari", None, "Pociąg, ok. 10 min do centrum."),
    "TRS": ("triest", None, "Pociąg lub autobus, ok. 40 min do centrum."),
    "CDG": ("paryz", "Charles de Gaulle", "Pociąg RER B, ok. 35 min do centrum."),
    "ORY": ("paryz", "Orly", "Metro linii 14, ok. 30 min do centrum."),
    "BVA": ("paryz", "Beauvais", "Autobus do Porte Maillot, ok. 1 h 15 min."),
    "NCE": ("nicea", None, "Tramwaj T2, ok. 25 min do centrum."),
    "MRS": ("marsylia", None, "Autobus do dworca Saint-Charles, ok. 25 min."),
    "LYS": ("lyon", None, "Tramwaj Rhônexpress, ok. 30 min do centrum."),
    "BOD": ("bordeaux", None, "Autobus 30'Direct, ok. 35 min do centrum."),
    "TLS": ("tuluza", None, "Tramwaj lub autobus, ok. 25 min do centrum."),
    "STN": ("londyn", "Stansted", "Pociąg Stansted Express, ok. 50 min do Liverpool Street."),
    "LTN": ("londyn", "Luton", "Kolejka DART + pociąg, ok. 45 min do St Pancras."),
    "LGW": ("londyn", "Gatwick", "Pociąg, ok. 30–45 min do centrum."),
    "LHR": ("londyn", "Heathrow", "Linia Elizabeth, ok. 35 min do centrum."),
    "SEN": ("londyn", "Southend", "Pociąg, ok. 55 min do Liverpool Street."),
    "EDI": ("edynburg", None, "Autobus Airlink 100 lub tramwaj, ok. 30 min."),
    "MAN": ("manchester", None, "Pociąg, ok. 20 min do centrum."),
    "LPL": ("liverpool", None, "Autobus, ok. 30 min do centrum."),
    "BRS": ("bristol", None, "Autobus A1 Airport Flyer, ok. 30 min."),
    "GLA": ("glasgow", None, "Autobus Airport Express 500, ok. 20 min."),
    "PIK": ("glasgow", "Prestwick", "Pociąg, ok. 50 min do Glasgow Central."),
    "BFS": ("belfast", None, "Autobus Airport Express 300, ok. 40 min."),
    "DUB": ("dublin", None, "Autobus Airlink lub Dublin Express, ok. 30 min."),
    "ORK": ("cork", None, "Autobus, ok. 25 min do centrum."),
    "BRU": ("bruksela", None, "Pociąg, ok. 20 min do centrum."),
    "CRL": ("bruksela", "Charleroi", "Autobus do dworca Bruxelles-Midi, ok. 55 min."),
    "AMS": ("amsterdam", None, "Pociąg, ok. 15 min do Amsterdam Centraal."),
    "EIN": ("eindhoven", None, "Autobus 400/401, ok. 25 min do dworca."),
    "RTM": ("rotterdam", None, "Autobus 33, ok. 20 min do centrum."),
    "LUX": ("luksemburg", None, "Autobus, ok. 20 min do centrum (komunikacja bezpłatna)."),
    "MUC": ("monachium", None, "S-Bahn S1/S8, ok. 40 min do centrum."),
    "FMM": ("monachium", "Memmingen", "Autobus do Monachium, ok. 1 h 40 min."),
    "HAM": ("hamburg", None, "S-Bahn S1, ok. 25 min do centrum."),
    "CGN": ("kolonia", None, "S-Bahn, ok. 15 min do dworca głównego."),
    "DUS": ("dusseldorf", None, "S-Bahn, ok. 12 min do centrum."),
    "NRN": ("dusseldorf", "Weeze", "Autobus do Düsseldorfu, ok. 1 h 15 min."),
    "FRA": ("frankfurt", None, "S-Bahn, ok. 15 min do centrum."),
    "HHN": ("frankfurt", "Hahn", "Autobus do Frankfurtu, ok. 1 h 45 min."),
    "VIE": ("wieden", None, "Pociąg CAT 16 min lub S7 ok. 25 min."),
    "SZG": ("salzburg", None, "Autobus, ok. 20 min do centrum."),
    "PRG": ("praga", None, "Autobus AE lub 119 + metro, ok. 35 min."),
    "BUD": ("budapeszt", None, "Autobus 100E, ok. 35 min do centrum."),
    "BTS": ("bratyslawa", None, "Autobus 61, ok. 25 min. Do Wiednia ok. 1 h autobusem."),
    "GVA": ("genewa", None, "Pociąg, ok. 7 min do centrum."),
    "ZRH": ("zurych", None, "Pociąg, ok. 12 min do centrum."),
    "BSL": ("bazylea", None, "Autobus 50, ok. 20 min do centrum."),
    "CPH": ("kopenhaga", None, "Metro, ok. 15 min do centrum."),
    "OSL": ("oslo", None, "Pociąg Flytoget, ok. 20 min do centrum."),
    "TRF": ("oslo", "Torp", "Autobus Torp-ekspressen do Oslo, ok. 1 h 50 min."),
    "BGO": ("bergen", None, "Kolej miejska Bybanen, ok. 45 min."),
    "ARN": ("sztokholm", "Arlanda", "Pociąg Arlanda Express, ok. 20 min."),
    "NYO": ("sztokholm", "Skavsta", "Autobus Flygbussarna, ok. 1 h 20 min."),
    "VST": ("sztokholm", "Västerås", "Autobus, ok. 1 h 15 min."),
    "GOT": ("goteborg", None, "Autobus Flygbussarna, ok. 30 min."),
    "MMX": ("malmo", None, "Autobus Flygbussarna, ok. 40 min."),
    "HEL": ("helsinki", None, "Pociąg, ok. 30 min do centrum."),
    "KEF": ("rejkiawik", None, "Autobus Flybus, ok. 45 min do centrum."),
    "RIX": ("ryga", None, "Autobus 22, ok. 30 min do centrum."),
    "TLL": ("tallinn", None, "Tramwaj 4, ok. 20 min do centrum."),
    "VNO": ("wilno", None, "Pociąg lub autobus, ok. 15 min do centrum."),
    "ATH": ("ateny", None, "Metro linii 3, ok. 40 min do centrum."),
    "SKG": ("saloniki", None, "Autobus 01X, ok. 45 min do centrum."),
    "SPU": ("split", None, "Autobus, ok. 30 min do centrum."),
    "DBV": ("dubrownik", None, "Autobus, ok. 30 min do starego miasta."),
    "ZAD": ("zadar", None, "Autobus, ok. 20 min do centrum."),
    "ZAG": ("zagrzeb", None, "Autobus, ok. 30 min do centrum."),
    "LJU": ("lublana", None, "Autobus, ok. 45 min do centrum."),
    "BEG": ("belgrad", None, "Autobus A1, ok. 30 min do centrum."),
    "SJJ": ("sarajewo", None, "Autobus, ok. 30 min do centrum."),
    "TIA": ("tirana", None, "Autobus, ok. 30 min do centrum."),
    "SOF": ("sofia", None, "Metro, ok. 25 min do centrum."),
    "OTP": ("bukareszt", None, "Autobus ekspresowy lub pociąg, ok. 45 min."),
    "BBU": ("bukareszt", "Băneasa", "Autobus, ok. 30 min do centrum."),
    "DTM": ("dortmund", None, "Autobus AirportExpress do dworca, ok. 25 min."),
    "RMO": ("kiszyniow", None, "Autobus lub trolejbus, ok. 30 min do centrum."),
    "OHD": ("ochryda", None, "Taksówka, ok. 15 min do starego miasta."),
    "MLA": ("malta", None, "Autobus X4, ok. 25 min do Valletty."),
    "IST": ("stambul", None, "Metro M11 lub autobus Havaist, ok. 1 h 15 min."),
    "SAW": ("stambul", "Sabiha Gökçen", "Autobus Havabus, ok. 1 h 15 min."),
}


def accent_for(key: str) -> str:
    return ACCENTS[zlib.crc32(key.encode()) % len(ACCENTS)]


def city_for_airport(iata: str) -> dict | None:
    """City metadata for a destination airport, or None when it is not a city-break destination."""
    a = AIRPORTS.get(iata)
    if not a:
        return None
    key, via, transfer = a
    name, country, cc, lat, lon, hotel_night, tagline = CITIES[key]
    return {"key": key, "name": name, "country": country, "cc": cc, "lat": lat, "lon": lon,
            "hotel_night": hotel_night, "tagline": tagline, "via": via, "transfer": transfer,
            "accent": accent_for(key), "airport": iata}
